[build]
  command = "ng build componentes && ng build perfil-personal --configuration=production && ng build comidas --configuration=production --base-href=/comidas/ && mkdir -p dist/perfil-personal/browser/comidas && cp -r dist/comidas/browser/* dist/perfil-personal/browser/comidas/"
  publish = "dist/perfil-personal/browser"

[[redirects]]
  from = "/comidas/*"
  to = "/comidas/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200