[build]
  command = "ng build componentes && ng build perfil-personal --configuration=production"
  publish = "dist/perfil-personal/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
